### ISSUE TITLE
When animation is not yet completed, right clicking too quickly again will throw you into the workspaces view

### ISSUE THREAD

**Issue by tenseoverflow** [mechtifs/usable-overview#1]
This extension is one of those good quality of life features that actually make sense to include in the stock install of GNOME. Probably should be pushed into GNOME 43.

This issue might not be that prevalent when daily using, however when right-clicking too fast again on the Activities button, it throws you into the workspaces view rather than the desktop view. When animation is done, it works fine, so probably not that severe of an issue, but will save half a second when accidentally right-clicking on the Activities button.

**Comment by mechtifs** [comment]
Sorry for the untimely reply! I've been quite busy on schoolwork these days :)
The issue is resolved by adding a timeout to check whether the animation is done, since GNOME does not provide an interface to check where the overview state is at.

Thank you for your feedback!
